## Python Basics

In [ ]:
1 + 2 * 3 

In [ ]:
2**3

In [ ]:
x = "Machine" + "Learning"
print (x)

In [ ]:
x.upper()

In [ ]:
x.lower()

In [ ]:
len(x)

In [ ]:
a = 2 + 3
b = a * 4
c = b - 7
L = [a,b,c]
print (L)

In [ ]:
M = [10, 2, "a", 3.5]
N = L + M
print (N)

In [ ]:
len(N)

In [ ]:
N[2]

In [ ]:
N[:3]

In [ ]:
N[3:]

In [ ]:
N[3:6]

In [ ]:
# This is what a comment looks like 
fruits = ['apples','oranges','pears','bananas']
for fruit in fruits:
    print (fruit + ' for sale')

fruitPrices = {'apples': 2.00, 'oranges': 1.50, 'pears': 1.75}
for fruit, price in fruitPrices.items():
    if price < 2.00:
        print ('%s cost %f a pound' % (fruit, price))
    else:
        print (fruit + ' are too expensive!')

In [ ]:
# Example of python's list comprehension construction:

nums = [1,2,3,4,5,6]
plusOneNums = [x+1 for x in nums]
print ("plusOneNums =", plusOneNums)
oddNums = [x for x in nums if x % 2 == 1]
print ("oddNums = ", oddNums)
oddNumsPlusOne = [x+1 for x in nums if x % 2 ==1]
print ("oddNumsPlusOn = ", oddNumsPlusOne)

In [ ]:
# Dictionaries

studentIds = {'knuth': 42.0, 'turing': 56.0, 'nash': 92.0 }
studentIds['turing']

In [ ]:
studentIds['ada'] = 97.0
studentIds

In [ ]:
del studentIds['knuth']
studentIds

In [ ]:
studentIds['knuth'] = [42.0,'forty-two']
studentIds

In [ ]:
studentIds.keys()

In [ ]:
studentIds.values()

In [ ]:
studentIds.items()

In [ ]:
len(studentIds) 

## Numpy

In [1]:
import numpy as np

In [2]:
# Creating a 1-d array

A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [3]:
# Creating a 1-d array from an existing Python list

L = [1, 2, 3, 4, 5, 6]

A = np.array(L)
A

array([1, 2, 3, 4, 5, 6])

In [ ]:
A / 5

In [4]:
np.array([1.0,2,3,4,5]) / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [6]:
M = np.array([2, 3, 4, 5, 6, 7])

P = L * M
P

array([ 2,  6, 12, 20, 30, 42])

In [7]:
P.sum()

112

In [ ]:
P.mean()

In [ ]:
# Dot product of two vectors

np.dot(L, M)

In [ ]:
# Creating a 2-d array

X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

In [ ]:
# Transpose a 2-d array

X.T

In [ ]:
# Array slicing

X[1,2]

In [ ]:
X[:,1]

In [ ]:
X[0,:]

In [ ]:
X[1:,1:]

In [ ]:
X[1:,0:2]

In [ ]:
# Using arrays to index into other arrays (e.g., Boolean masks)

A = np.array([1, 2, 3, 4, 5, 6])

A > 3

In [ ]:
A[A > 3]

In [ ]:
sum(A[A > 3])

In [ ]:
Ind = (A > 1) & (A < 6)
print (Ind)
A[Ind]